### ISSUE TITLE
Adding holes and tplace issue

### ISSUE THREAD

**Issue by MohannadRawashdeh** [Lobo-T/RPI-Pico-Eagle-lib#1]
Hello
Good work.
I checked the library, you only missed the 4 holes 2.1mm on the board.
For the board outline you draw on layer#21 , it's better to draw the line over the SMD pads (like in PICO-PKG) on tDoc #51 for example.

**Comment by Lobo-T** [comment]
The mounting holes?  No, I have not missed them, I have omitted them.  I have no use were I would need that strong mechanical connection, and having  them would just make routing harder.
