### ISSUE TITLE
footprint error

### ISSUE THREAD

**Issue by peterjazenga** [Lobo-T/RPI-Pico-Eagle-lib#2]
I have Pico on my desk and I noticed there are three test points directly under the USB connector which could be short circuited by the SMD footprint

**Comment by Lobo-T** [comment]
The area under the USB connector is tRestrict for this reason.  It's not copper.  Eagle uses the same colour by default.

![restrict](https://user-images.githubusercontent.com/13045607/186428325-ebdcf765-d172-4d77-acda-617512461fd7.png)
